repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: no-shell-prompt-fragments
        name: Detect shell prompt fragments
        entry: scripts/check_prompt_fragments.py
        language: python
        types: [python]
        exclude: ^scripts/check_prompt_fragments\.py$
