version: "3.8"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - seer_db:/app/data
    ports:
      - "8000:8000"
    environment:
      - LLM_PROVIDER=${LLM_PROVIDER:-groq}
      - LLM_MODEL=${LLM_MODEL:-llama3-8b-8192}
      - GROQ_API_KEY=${GROQ_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - DB_PATH=${DB_PATH:-/app/data/seer.db}

volumes:
  seer_db: 