version: "3.8"

services:
  # UI Service (WebSocket, tick generation, frontend)
  ui:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
    ports:
      - "8000:8000"
    environment:
      - LLM_PROVIDER=${LLM_PROVIDER:-groq}
      - LLM_MODEL=${LLM_MODEL:-llama3-8b-8192}
      - GROQ_API_KEY=${GROQ_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - DB_PATH=${DB_PATH:-/app/data/whispr.db}
      - USE_REAL_DATA=${USE_REAL_DATA:-false}
      - TRADING_SYMBOL=${TRADING_SYMBOL:-SPY}
      - LIVE_TRADING=${LIVE_TRADING:-false}
    depends_on:
      - rules-engine

  # Rules Engine Service (Pure rule evaluation logic)
  rules-engine:
    build:
      context: .
      dockerfile: services/rules_engine/Dockerfile
    volumes:
      - ./backend/data:/app/data
    ports:
      - "8001:8001"
    environment:
      - LLM_PROVIDER=${LLM_PROVIDER:-groq}
      - LLM_MODEL=${LLM_MODEL:-llama3-8b-8192}
      - GROQ_API_KEY=${GROQ_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - DB_PATH=${DB_PATH:-/app/data/whispr.db}

volumes:
  whispr_db: 